image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo build --features kvm,virtualbox,xen

vscode:
  extensions:
    - editorconfig.editorconfig
    - matklad.rust-analyzer
    - eamodio.gitlens
    - serayuzgur.crates
    - belfz.search-crates-io
    - bungcip.better-toml

github:
  prebuilds:
    branches: true
    addCheck: false
    addComment: true
