name: Doc

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build docs
        run: cargo doc

  book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-mdbook

      - name: install mdbook
        run: cargo install mdbook

      - name: build doc
        run: mdbook build doc
