name: Doc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build docs
        run: cargo doc
